# Generated by Django 5.1.7 on 2025-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expenses', 'expenses')], default='expenses', max_length=20),
        ),
    ]
