# Generated by Django 5.1.7 on 2025-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], default='expense', max_length=20),
        ),
    ]
