# Generated by Django 5.2.5 on 2026-06-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_income_date'),
    ]

    operations = [
    ]
